# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Global Dependencies
	parchment_mc_version=1.21.4
	parchment_version=2025.03.16

# Fabric Properties
    # check these on https://fabricmc.net/develop
    minecraft_version=1.21.4
    yarn_mappings=1.21.4+build.1
    loader_version=0.16.9

# Fabric Dependencies
	fabric_version=0.111.0+1.21.4

# Neoforge Properties
	neo_version=21.4.114-beta
	neo_version_range=[21.3.0-beta,)
	neo_loader_version_range=[4,)
#this ones from forge i think, but still used
	minecraft_version_range=[1.21.4,1.22)

# Mod Properties
	mod_id = coroutil
	mod_name=CoroUtil
	mod_version = 1.21.4-1.3.8
	mod_description=It utils
	maven_group = com.corosus.coroutil
	archives_base_name = coroutil
	mod_authors=Corosus
	mod_license=All Rights Reserved

