modLoader="javafml"
loaderVersion="[43,)"
license="All Rights Reserved"

[[mods]]
modId="coroutil"
version="${file.jarVersion}"
displayName="CoroUtil"
authors="Corosus"
description='''
Library for Corosus mods
'''