name: Java CI with Gradle

on: [push]
jobs:

  jdk17:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: --settings-file build_neoforge_settings.gradle build

    - name: Locate built JARfile
      id: jar
      run: echo "##[set-output name=jarfile;]$(find build/libs/ -name "*.jar" -not -name "*slim*" -not -name "*source*")"

    - name: Set Artifact name
      id: jarname
      run: echo "##[set-output name=jarname;]$(find build/libs/ -name "*.jar" -not -name "*slim*" -not -name "*source*" | sed 's:.*/::')"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.jarname.outputs.jarname }}
        path: ${{ steps.jar.outputs.jarfile }}
        retention-days: 90

